FROM centos:latest
MAINTAINER NewstarCorporation
RUN yum -y install httpd
RUN wget -O https://github.com/arvindpathare/MSRcosmos_test/Creation of container/index.html
COPY index.html /var/www/html/
CMD [“/usr/sbin/httpd”, “-D”, “FOREGROUND”]
EXPOSE 80